version: '3'

#prometheus server
#access port 9090
services:
  prometheus:
    image: prom/prometheus
    expose:
      - 9090
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
#configuration file to scrape prom pushgatewaay
  pushgateway:
    image: prom/pushgateway
    expose:
      - 9091
    ports:
      - 9091:9091